#!/usr/bin/python

import os, sys,argparse
from classes.samples import Samples
from classes.ux import MsgUser

class readable_dir(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        prospective_dir=values
        if not os.path.isdir(prospective_dir):
            raise argparse.ArgumentTypeError("readable_dir:{0} is not a valid path".format(prospective_dir))
        if os.access(prospective_dir, os.R_OK):
            setattr(namespace,self.dest,prospective_dir)
        else:
            raise argparse.ArgumentTypeError("readable_dir:{0} is not a readable dir".format(prospective_dir))

            
            
#rootDir=sys.argv[1] 
ldir="."
parser = argparse.ArgumentParser(description='Connectomics and Reporting User Shell is used to iterrogate samples, generate or extract measurements.')
parser.add_argument('-samples', action=readable_dir,default=ldir,help="Path to patient samples")
parser.add_argument('-status', action="status",help="Report back what is out there and what needs to be done")
parser.add_argument('-recon',action='recon',help='Apply recon-all for any T1.mgz found beneath working folder')
parser.add_argument('-norender',action='norender',default='n',help='If there are incomplete connectomes, ignore the outstanding work'
parser.add_argument('-rebuild', action='store_true',
                    help='Recreate any intermediary files used for establishing measurements.  If this not specified, any intermetiate files found with the appriate file name will be left untouched.')
parser.add_argument('-patient', action='store',
                    help='Specify patient ID of interest if focusing on a single patient')
parser.add_argument('-voi',action='store',
                   help='Values of Interest - Path to text file that lists values of interest to extract.  One column per line.  Look at any patient sample tractography\\crush\\tracts.txt file for measures.')
args = parser.parse_args()

S=Samples(args.samples,args.rebuild,args.voi)

#Read VOI into array
if (args.voi):
    
    if os.path.isfile("%s" %(args.voi)):
        #Print Header    
        with open(args.voi) as f:
                content = f.readlines()
                content = [x.strip() for x in content] #Remove Whitespace
                print(",".join(content))


        for p in S.Patients:
            if (args.patient is not None and args.patient != p.Id):
                continue
            #Print values from each patient visit
            for v in p.Visits:
                v.Report()
    else:
        print("voi file not found (%s)" %(args.voi))
            

else:

    print("################## CRUSH ##################")
    print("#  Connectomics and Reporting User Shell  #")
    print("###########################################")
    if S.Patients:
        print("%i patients" % (len(S.Patients)))
    else:
        print("No patient samples found in path [%s].  Specify -samples for alternate path." %(args.samples))

    
	#STATUS REPORT ############################################################
	if (args.status):
		l_v=0
		print("Sample size:%i" %(len(S.Patients)))
		print(
		for p in S.Patients:
			if (args.patient is not None and args.patient != p.Id):
				continue
			l_v+=len(p.Visits))
			
		print(
		for p in S.Patients:
			if (args.patient is not None and args.patient != p.Id):
				continue
			for v in p.Visits:
				
				if v.ReconComplete != True:
					l_reconall_message="Cortical Reconstruction Complete"
				else 
					l_reconall_message="Cortical Reconstruction INCOMPLETE"
					
				if v.ReconComplete != True:
					l_parcellation_message="NOT Parcellated"
				else 
					l_parcellation_message="Parcellated"
					
				if v.MeasurementComplete != True:
					l_measurement_message="NO Measurements"
				else 
					l_measurement_message="Measurement Complete"

			print("%s/%s %s, %s, %s" % (p.Id, len(p.Visits), l_reconall_message,l_parcellation_message,l_measurement_message))
		
	
	#RENDER ANYTHING OUTSTANDING ##############################################
	if (args.norender!='n'):
		for p in S.Patients:
			if (args.patient is not None and args.patient != p.Id):
				continue
			for v in p.Visits:

				if v.ReconComplete != True:
					MsgUser.warning("\t%s recon incomplete" %(v.Id))
				else:
					v.Render()
					v.Measure()





    MsgUser.ok("We are done") 
